services:
  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./blogdb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
  blog-py:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - user=admin
      - pass=pass123
